# Generated by Django 3.1.2 on 2020-10-16 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0002_auto_20201016_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
