# Generated by Django 3.1.2 on 2020-10-16 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0005_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
