# Generated by Django 3.1.2 on 2020-10-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0006_delete_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
