# Generated by Django 3.1.2 on 2020-10-17 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0007_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default='', upload_to='post_images/'),
        ),
    ]
