# Generated by Django 3.1.2 on 2020-10-17 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0003_productcomments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductComments',
        ),
    ]
