# Generated by Django 3.1.2 on 2020-10-17 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0007_productcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcomments', to='salesapp.product'),
        ),
    ]
